#goal definition

# Whether to perform all 4 stages: Headlands, Swath (Required), Route, Path
bool generate_headland True
bool generate_route True
bool generate_path True

# The field specification to use.
# If providing gml file with multiple fields, specify which with gml_field_id
# If using polygons, bounding polygon must be first, followed by inner cutouts
# Both must specify if the data is cartesian or GPS coordinates
bool frame_cartesian True
bool use_gml_file False
string gml_field
uint16 gml_field_id 0
nav2_complete_coverage_msgs/Coordinates[] polygons
string frame_id map

# Modes of operation of each stage, if used
nav2_complete_coverage_msgs/HeadlandMode headland_mode
nav2_complete_coverage_msgs/SwathMode swath_mode
nav2_complete_coverage_msgs/RouteMode route_mode
nav2_complete_coverage_msgs/PathMode path_mode

---
#result definition

# Error codes
# Note: The expected priority order of the errors should match the message order
uint16 NONE=0
uint16 INTERNAL_F2C_ERROR=801
uint16 INVALID_MODE_SET=802
uint16 INVALID_REQUEST=803
uint16 INVALID_COORDS=803

nav_msgs/Path nav_path
nav2_complete_coverage_msgs/PathComponents coverage_path
builtin_interfaces/Duration planning_time
uint16 error_code

---
#feedback definition
